# Change these first
owner: usthing # Your GitHub organization or username, where this repository lives
repo: web-upptime # The name of this repository

sites:
  - name: Home
    url: https://usthing.xyz
  - name: API: Campus Services
    url: https://campus-services.api.usthing.xyz/v1/categories
  - name: API: MS Proxy
    url: https://ms.api.usthing.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usthing.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: USThing Status
  introTitle: "USThing Status Page"
  introMessage: "This status page is powered by **Upptime**, the open-source uptime monitor and status page."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
